Models/Auction.cs
using System;
using System.Collections.Generic; // to use Lists
using System.ComponentModel.DataAnnotations.Schema;

namespace Auctions.Models
{
    public class Auction
    {
        public int AuctionId {get;set;}
        public string Name {get;set;}
        public string Description {get;set;}
        public int SellerId { get;set;}
        public User Seller {get;set;}
        public float StartBid {get;set;}
        public int HighestBid {get;set;}
        public DateTime EndDate {get;set;}
        public DateTime CreatedAt {get;set;}
        public DateTime UpdatedAt {get;set;}
        public List<Bid> Bids {get;set;}
        public Auction()
        {
            Bids = new List<Bid>();
        }
    }



}

Models/AuctionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions; // Password regex

namespace Auctions.Models
{
    public class AuctionViewModel
    {
        [Required(ErrorMessage = "Product name is required")]
        [MinLength(3, ErrorMessage = "Product name must be at least 3 characters")]
        [DataType(DataType.Text)]
        public string Name {get;set;}

        [Required(ErrorMessage = "Product description is required")]
        [MinLength(10, ErrorMessage = "Product description must be at least 10 characters")]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Starting bid is required")]
        [MinValue]
        public float Bid {get;set;}

        [Required(ErrorMessage = "End date is required")]
        [ValidateDate]
        [DataType(DataType.Date)]
        public DateTime EndDate {get;set;}
    }
    public class MinValue : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if((float)value>0)
            {
                return ValidationResult.Success;
            }
            return new ValidationResult("Starting bid is required");
        }
    } 
    public class ValidateDate : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            DateTime Today = DateTime.Now;
            if ((DateTime)value >= Today)
            {
                return ValidationResult.Success;
            }
            return new ValidationResult("Cannot have your end date in the past");
        }
    }
}

Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Auctions.Models;
using Microsoft.AspNetCore.Http; // to use Sessions
using Microsoft.EntityFrameworkCore; // use Entity
using Microsoft.AspNetCore.Identity;

namespace Auctions.Controllers
{
    public class AuctionController : Controller
    {
        private AuctionContext _context { get; set; }
        public AuctionController(AuctionContext context)
        {
            _context = context;
        }
        private User GetLoggedUser()
        {
            return _context.Users.SingleOrDefault(user => user.UserId == (int)HttpContext.Session.GetInt32("UserId"));
        }
        private List<Auction> GetAuctions()
        {
            return _context.Auctions.Include(a=>a.Seller).Include(a=>a.Bids).ThenInclude(bb=>bb.Bidder).OrderBy(aa=>aa.EndDate).ToList();
        }
        private List<Auction> CheckAuction()
        {
            List<Auction> Auctions = GetAuctions();
            foreach(Auction auction in Auctions)
            {
                TimeSpan Remain = auction.EndDate - DateTime.Now;
                if(Remain.Days<=0)
                {
                    if(auction.Bids.Count>0)
                    {
                        User TopBidder = _context.Users.SingleOrDefault(u=>u.UserId==auction.HighestBid);
                        TopBidder.Wallet = TopBidder.Wallet - auction.StartBid;
                        auction.Seller.Wallet = auction.Seller.Wallet + auction.StartBid;
                    }
                    _context.Auctions.Remove(auction);
                    foreach(Bid bid in auction.Bids)
                    {
                        _context.Bids.Remove(bid);
                    }
                }
            }
            _context.SaveChanges();
            return GetAuctions();
        }
        [HttpGet]
        [Route("dashboard")]
        public IActionResult Dashboard()
        {
            if(HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.LoggedUser = GetLoggedUser();
            ViewBag.Auctions = CheckAuction();
            return View();
        }
        [HttpGet]
        [Route("Auction/New")]
        public IActionResult New()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        [Route("Auction/Create")]
        public IActionResult Create(AuctionViewModel model)
        {
            if(ModelState.IsValid)
            {
                Auction NewAuction = new Auction(); 
                NewAuction.Name = model.Name; 
                NewAuction.Description = model.Description;
                NewAuction.SellerId = (int)HttpContext.Session.GetInt32("UserId"); 
                NewAuction.StartBid = model.Bid; 
                NewAuction.EndDate =  model.EndDate; 
                NewAuction.CreatedAt = DateTime.Now;
                NewAuction.UpdatedAt = DateTime.Now;
                _context.Auctions.Add(NewAuction);
                _context.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            return View("New");
        }
        [HttpGet]
        [Route("Auction/Show/{AuctionId}")]
        public IActionResult Show(int AuctionId)
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Auction = _context.Auctions.Include(a=>a.Seller).Include(a=>a.Bids).ThenInclude(bb=>bb.Bidder).SingleOrDefault(aa=>aa.AuctionId==AuctionId);
            return View();
        }
        [HttpPost]
        [Route("Auction/NewBid/{AuctionId}")]
        public IActionResult NewBid(int AuctionId, BidViewModel model)
        {
            Auction Auction = _context.Auctions.Include(a => a.Seller).Include(a => a.Bids).ThenInclude(bb => bb.Bidder).SingleOrDefault(aa => aa.AuctionId == AuctionId);
            ViewBag.Auction = Auction;
            User LoggedUser = GetLoggedUser();
            if(ModelState.IsValid)
            {
                if(Auction.SellerId==LoggedUser.UserId)
                {
                    ViewBag.TooLow = "You cannot place bids on your own item";
                } else {
                    if (model.Bid > LoggedUser.Wallet)
                    {
                        ViewBag.TooLow = "You do not have enough money in your wallet";
                    }
                    else
                    {
                        if (model.Bid < Auction.StartBid)
                        {
                            ViewBag.TooLow = "Bid cannot be less than highest bid";
                        }
                        else
                        {
                            Bid NewBid = new Bid();
                            NewBid.Amount = model.Bid;
                            NewBid.AuctionId = Auction.AuctionId;
                            NewBid.UserId = (int)HttpContext.Session.GetInt32("UserId");
                            Auction.StartBid = model.Bid;
                            Auction.HighestBid = (int)HttpContext.Session.GetInt32("UserId");
                            _context.Bids.Add(NewBid);
                            _context.SaveChanges();
                            return RedirectToAction("Dashboard");
                        }
                    }
                }
            }
            return View("Show"); 
        }
        [HttpPost]
        [Route("Auction/Delete/{AuctionId}")]
        public IActionResult Delete(int AuctionId)
        {
            Auction RemoveAuction = _context.Auctions.Include(a => a.Seller).Include(a => a.Bids).ThenInclude(bb => bb.Bidder).SingleOrDefault(aa=>aa.AuctionId==AuctionId);
            _context.Auctions.Remove(RemoveAuction);
            foreach (Bid bid in RemoveAuction.Bids)
            {
                _context.Bids.Remove(bid);
            }
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Auction/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard"; 
    Layout = "_Layout"; 
    var logged = ViewBag.LoggedUser;
}
<h1>Welcome, @logged.FirstName!</h1>
<div class="container">
    <label>Your Current Wallent:</label> $@logged.Wallet
</div>
<h2>Current Auctions</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Product</th>
            <th>Seller</th>
            <th>Top Bid</th>
            <th>Time Remaining</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var auction in ViewBag.Auctions)
        {
            TimeSpan Remain = auction.EndDate-DateTime.Now;
            <tr>
                <td><a href="/Auction/Show/@auction.AuctionId">@auction.Name</a></td>
                <td>@auction.Seller.Username</td>
                <td>@auction.StartBid</td>
                <td>@Remain.Days days</td>
                <td>
                    @{
                        if(auction.SellerId==logged.UserId) {
                            <form action="/Auction/Delete/@auction.AuctionId" method="POST">
                                <button class="btn btn-link">Delete</button>
                            </form>
                        }
                        else 
                        {
                            <form action="/Auction/Show/@auction.AuctionId">
                                <button class="btn btn-link">Check Auction</button>
                            </form>
                        }
                    }
                    
                </td>
            </tr>
        }
    </tbody>
</table>
<form action="Auction/New" method="GET">
    <button class="btn btn-info">New Auction</button>
</form>

Views/Auction/New.cshtml
@{
    ViewData["Title"] = "New Auction"; 
    Layout = "_Layout"; 
}
<h2>New Auction</h2>
    <div class="container">
         @model Auctions.Models.AuctionViewModel
        <form asp-controller="Auction" asp-action="Create" method="POST">
            <div class="form-group">
                <label asp-for="Name">Name:</label>
                <span class="err" asp-validation-for="Name"></span>
                <input class="form-control" asp-for="Name">
            </div>
            <div class="form-group">
                <label asp-for="Description">Description:</label>
                <span class="err" asp-validation-for="Description"></span>
                <input class="form-control" asp-for="Description">
            </div>
            <div class="form-group">
                <label asp-for="Bid">Starting Bid:</label>
                <span class="err" asp-validation-for="Bid"></span>
                <input class="form-control" asp-for="Bid">
            </div>
            <div class="form-group">
                <label asp-for="EndDate">End Date:</label>
                <span class="err" asp-validation-for="EndDate"></span>
                <input type="Date" class="form-control" asp-for="EndDate">
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>

Views/Auction/Show.cshtml
@{
    ViewData["Title"] = "New Auction"; 
    Layout = "_Layout"; 
    var auction = ViewBag.Auction;
}
<h2>@auction.Name</h2>
<div class="container">
    <div class="form-group">
        <label>Created By:</label> @auction.Seller.FirstName @auction.Seller.LastName
    </div>
    <div class="form-group">
        @{
             TimeSpan Remain = auction.EndDate-DateTime.Now;
        }
        <label>Time Remaining:</label> @Remain.Days days
    </div>
    <div class="form-group">
        <p>@auction.Description</p>
    </div>
    <div class="form-group">
        @{
            float TopBid = auction.StartBid;
            int index = 0;
            if(auction.Bids.Count>0)
            {
                TopBid = auction.Bids[0].Amount;
                for(int i=1; i<auction.Bids.Count; i++)
                {   
                    if(TopBid<auction.Bids[i].Amount)
                    {
                        index = i; 
                        TopBid=auction.Bids[i].Amount;
                    }
                }
                <h2>Higest Bidder: @auction.Bids[index].Bidder.Username</h2>
            } 
        }
        <div>
            <h3 style="display:inline-block;">Current Highest Bid:</h3>
            <h2 style="display:inline-block;">$@TopBid</h2>
        </div>
    </div>
    <div class="container">
         @model Auctions.Models.BidViewModel
         <h4>Place your bid:</h4>
        <form action="/Auction/NewBid/@auction.AuctionId" method="POST">
            <span class="err" asp-validation-for="Bid"></span>
            @if(ViewBag.TooLow!=null)
            {
                <span class="err">@ViewBag.TooLow</span>
            }
            <input class="form-control" asp-for="Bid" placeholder="Your bid goes here">
            <button type="submit" class="btn btn-primary">Bid</button>
        </form>
    </div>
</div>